### ISSUE TITLE
Support new app loading style

### ISSUE THREAD

**Issue by jjkester** [jjkester/django-auditlog#33]
**Todo list**
- [x] Create app config
- [x] Set app config in ```__init__.py```
- [ ] Document app config

**Considerations**
- Check if anything needs to be moved to ```AppConfig.ready()``` (signals e.d.)

**Comment by jjkester** [comment]
App config todo's done in 4bb432b

**Comment by jjkester** [comment]
Since the new app loading does not require any additional knowledge from users, I do not think it should be documented since the installation procedure has not changed. I consider this issue done.
